#!/bin/bash

# A bash script to update a Cloudflare DNS A record with the external IP of the source machine
# Used to provide DDNS service for my home
# Needs the DNS record pre-creating on Cloudflare

# Proxy - uncomment and provide details if using a proxy
#export https_proxy=http://<proxyuser>:<proxypassword>@<proxyip>:<proxyport>

# Cloudflare zone is the zone which holds the record
zone=valmikikothare.com
# dnsrecord is the A record which will be updated
dnsrecord=tabletop.valmikikothare.com

## Cloudflare authentication details
## keep these private
cloudflare_auth_email=valmiki.kothare.vk@gmail.com
cloudflare_auth_key=mntN9G3NWGLuoPlmkZcx8wHPyQDMsTJvdFIfFRUw


# Get the current external IP address
ip=$(hostname -I | awk '{print $1}')

echo "Current IP is $ip"

if host $dnsrecord 1.1.1.1 | grep "has address" | grep "$ip"; then
  echo "$dnsrecord is currently set to $ip; no changes needed"
  exit
fi

# if here, the dns record needs updating

# get the zone id for the requested zone
zone_id=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone" \
  -H "Authorization: Bearer $cloudflare_auth_key" \
  -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id')

echo "Zone ID for $zone is $zone_id"

# get the dns record id for the requested record
record_id=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records?name=$dnsrecord" \
  -H "Authorization: Bearer $cloudflare_auth_key" \
  -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id')

echo "Record ID for $dnsrecord is $record_id"

# update the dns record with the new IP
update=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_id/dns_records/$record_id" \
  -H "Authorization: Bearer $cloudflare_auth_key" \
  -H "Content-Type: application/json" \
  --data '{"type":"A","name":"'$dnsrecord'","content":"'$ip'","ttl":120,"proxied":false}')

if echo "$update" | grep -q '"success":true'; then
  echo "Successfully updated $dnsrecord to $ip"
else
  echo "Failed to update $dnsrecord"
fi
